# The signing key.
#
# This is the root of trust for the whole build. Everything downstream is a
# question of who can ask this key to sign, and the answer is one service
# account, from one Cloud Build step, after one scan returned clean.
#
# Asymmetric on purpose. The private key never leaves KMS and the verifier only
# ever holds the public half, so Binary Authorization in the runtime project can
# check a signature without being able to produce one. A symmetric HMAC would
# mean the verifier could forge exactly what it verifies.

resource "google_kms_key_ring" "attestation" {
  project  = google_project.build.project_id
  name     = "attestation"
  location = var.region

  depends_on = [google_project_service.build]
}

resource "google_kms_crypto_key" "attestor" {
  # checkov:skip=CKV_GCP_82: prevent_destroy would make this repo undestroyable,
  # and it is built to be deployed, demonstrated, and torn down. In a standing
  # environment this should be true, because losing the key invalidates every
  # attestation ever made with it and there is no way to re-sign history.
  name     = "binauthz-attestor"
  key_ring = google_kms_key_ring.attestation.id
  purpose  = "ASYMMETRIC_SIGN"

  version_template {
    algorithm        = var.kms_signing_algorithm
    protection_level = var.kms_protection_level
  }

  # No rotation schedule, and that is not an oversight. KMS cannot auto-rotate
  # an asymmetric signing key, because rotation would create a version whose
  # public key no attestor knows about, and every signature made with it would
  # fail verification. Rotation here is a deliberate two-step: add the new
  # version's public key to the attestor, then switch signing over to it.
  lifecycle {
    prevent_destroy = false
  }
}

# The public half, read back so the attestor can be configured with it. This is
# a data source rather than a hardcoded PEM because the PEM is generated by KMS
# at key creation and is not knowable before apply.
data "google_kms_crypto_key_version" "attestor" {
  crypto_key = google_kms_crypto_key.attestor.id
}
