name: Guardrails

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  static:
    uses: jordann6/platform-guardrails/.github/workflows/tf-ci.yml@v1
    with:
      terraform_dir: terraform

  bootstrap:
    uses: jordann6/platform-guardrails/.github/workflows/tf-ci.yml@v1
    with:
      terraform_dir: bootstrap
